const leoAndGoPrices = {
    smallCars: {
        registrationFee: "GRATUITS",
        unlockFee: "1 €",
        durations: [
            { duration: "1 minute", price: "0,34 €", kmIncluded: "100 km" },
            { duration: "30 minutes", price: "8 €", kmIncluded: "100 km" },
            { duration: "1 heure", price: "14 €", kmIncluded: "100 km" },
            { duration: "2 heures", price: "23 €", kmIncluded: "100 km" },
            { duration: "3 heures", price: "29 €", kmIncluded: "100 km" },
            { duration: "6 heures", price: "45 €", kmIncluded: "100 km" },
            { duration: "1 jour", price: "59 €", kmIncluded: "100 km" },
            { duration: "2 jours", price: "109 €", kmIncluded: "200 km" },
            { duration: "3 jours", price: "159 €", kmIncluded: "300 km" },
            { duration: "4 jours", price: "199 €", kmIncluded: "400 km" },
            { duration: "5 jours", price: "239 €", kmIncluded: "500 km" },
            { duration: "6 jours", price: "279 €", kmIncluded: "600 km" },
            { duration: "7 jours", price: "319 €", kmIncluded: "700 km" },
            { duration: "8 jours", price: "359 €", kmIncluded: "800 km" },
            { duration: "9 jours", price: "399 €", kmIncluded: "900 km" },
            { duration: "10 jours", price: "439 €", kmIncluded: "1000 km" },
            { duration: "11 jours", price: "479 €", kmIncluded: "1100 km" },
            { duration: "12 jours", price: "519 €", kmIncluded: "1200 km" },
            { duration: "13 jours", price: "559 €", kmIncluded: "1300 km" },
            { duration: "14 jours", price: "599 €", kmIncluded: "1400 km" },
            { note: "Chaque kilomètre supplémentaire sera facturé 0,30 € TTC." },
        ],
    },
    biggerCars: {
        registrationFee: "GRATUITS",
        unlockFee: "1 €",
        durations: [
            { duration: "1 minute", price: "0,34 €", kmIncluded: "100 km" },
            { duration: "30 minutes", price: "8 €", kmIncluded: "100 km" },
            { duration: "1 heure", price: "14 €", kmIncluded: "100 km" },
            { duration: "2 heures", price: "23 €", kmIncluded: "100 km" },
            { duration: "3 heures", price: "32 €", kmIncluded: "100 km" },
            { duration: "6 heures", price: "49 €", kmIncluded: "100 km" },
            { duration: "1 jour", price: "69 €", kmIncluded: "100 km" },
            { duration: "2 jours", price: "119 €", kmIncluded: "200 km" },
            { duration: "3 jours", price: "169 €", kmIncluded: "300 km" },
            { duration: "4 jours", price: "209 €", kmIncluded: "400 km" },
            { duration: "5 jours", price: "249 €", kmIncluded: "500 km" },
            { duration: "6 jours", price: "289 €", kmIncluded: "600 km" },
            { duration: "7 jours", price: "329 €", kmIncluded: "700 km" },
            { duration: "8 jours", price: "369 €", kmIncluded: "800 km" },
            { duration: "9 jours", price: "409 €", kmIncluded: "900 km" },
            { duration: "10 jours", price: "449 €", kmIncluded: "1000 km" },
            { duration: "14 jours", price: "609 €", kmIncluded: "1400 km" },
            { note: "Chaque kilomètre supplémentaire sera facturé 0,30 € TTC." },
        ],
    },
    airportCars: {
        unlockFee: "1 €",
        durations: [
            { duration: "Forfait 30 minutes", price: "8 €", kmIncluded: "100 km" },
            { duration: "Forfait aéroport", price: "+9,99 €", kmIncluded: "N/A" },
            { note: "Total moyen : 20 €" },
        ],
    },
    preBookCar: {
        cost: "10 €",
        accessories: [
            { accessory: "Sièges enfants", price: "10 €/jour" },
            { accessory: "Chaînes hiver", price: "10 €/jour" },
        ],
    },
    utilityVehicles3m3: {
        registrationFee: "GRATUITS",
        unlockFee: "1 €",
        durations: [
            { duration: "1 minute", price: "0,34 €", kmIncluded: "100 km" },
            { duration: "30 minutes", price: "8 €", kmIncluded: "100 km" },
            { duration: "1 heure", price: "14 €", kmIncluded: "100 km" },
            { duration: "2 heures", price: "23 €", kmIncluded: "100 km" },
            { duration: "3 heures", price: "29 €", kmIncluded: "100 km" },
            { duration: "6 heures", price: "45 €", kmIncluded: "100 km" },
            { duration: "1 jour", price: "59 €", kmIncluded: "100 km" },
            { duration: "2 jours", price: "109 €", kmIncluded: "200 km" },
            { duration: "3 jours", price: "159 €", kmIncluded: "300 km" },
            { duration: "4 jours", price: "199 €", kmIncluded: "400 km" },
            { duration: "5 jours", price: "239 €", kmIncluded: "500 km" },
            { duration: "6 jours", price: "279 €", kmIncluded: "600 km" },
            { duration: "7 jours", price: "319 €", kmIncluded: "700 km" },
            { duration: "8 jours", price: "359 €", kmIncluded: "800 km" },
            { duration: "9 jours", price: "399 €", kmIncluded: "900 km" },
            { duration: "10 jours", price: "439 €", kmIncluded: "1000 km" },
            { duration: "11 jours", price: "479 €", kmIncluded: "1100 km" },
            { duration: "12 jours", price: "519 €", kmIncluded: "1200 km" },
            { duration: "13 jours", price: "559 €", kmIncluded: "1300 km" },
            { duration: "14 jours", price: "599 €", kmIncluded: "1400 km" },
            { note: "Chaque kilomètre supplémentaire sera facturé 0,30 € TTC." },
        ],
    },
    utilityVehicles6m3: {
        registrationFee: "GRATUITS",
        unlockFee: "1 €",
        durations: [
            { duration: "1 minute", price: "0,39 €", kmIncluded: "100 km" },
            { duration: "3 heures", price: "39 €", kmIncluded: "100 km" },
            { duration: "6 heures", price: "59 €", kmIncluded: "100 km" },
            { duration: "1 jour", price: "79 €", kmIncluded: "100 km" },
            { duration: "2 jours", price: "149 €", kmIncluded: "200 km" },
            { duration: "3 jours", price: "209 €", kmIncluded: "300 km" },
            { duration: "4 jours", price: "269 €", kmIncluded: "400 km" },
            { duration: "5 jours", price: "329 €", kmIncluded: "500 km" },
            { duration: "6 jours", price: "389 €", kmIncluded: "600 km" },
            { duration: "7 jours", price: "449 €", kmIncluded: "700 km" },
            { duration: "8 jours", price: "509 €", kmIncluded: "800 km" },
            { duration: "9 jours", price: "569 €", kmIncluded: "900 km" },
            { duration: "10 jours", price: "629 €", kmIncluded: "1000 km" },
            { duration: "14 jours", price: "869 €", kmIncluded: "1400 km" },
            { note: "Chaque kilomètre supplémentaire sera facturé 0,30 € TTC." },
        ],
    },
    teslaCars: {
        allRates: "Tout inclus",
        durations: [
            { duration: "4 heures", price: "59 €", kmIncluded: "100 km" },
            { duration: "1 jour", price: "69 €", kmIncluded: "100 km" },
            { duration: "2 jours", price: "129 €", kmIncluded: "200 km" },
            { duration: "3 jours", price: "189 €", kmIncluded: "300 km" },
            { duration: "4 jours", price: "239 €", kmIncluded: "400 km" },
            { duration: "5 jours", price: "289 €", kmIncluded: "500 km" },
            { duration: "6 jours", price: "339 €", kmIncluded: "600 km" },
            { duration: "7 jours", price: "389 €", kmIncluded: "700 km" },
            { duration: "8 jours", price: "439 €", kmIncluded: "800 km" },
            { duration: "9 jours", price: "489 €", kmIncluded: "900 km" },
            { duration: "10 jours", price: "539 €", kmIncluded: "1000 km" },
            { duration: "14 jours", price: "759 €", kmIncluded: "1400 km" },
            { note: "Chaque kilomètre supplémentaire sera facturé 0,30 € TTC." },
        ],
    },
};

export default leoAndGoPrices;
